version: "3.8"

services:
  server:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
    command: python3 main.py

  client:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:cached
    command: npm start
