version: "3.7"

services:
    db:
        image: postgres:latest
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: db
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
    users_service:
        build: ./users_service
        volumes:
            - ./users_service/:/app
        ports:
            - "8001:8000"
        environment:
            DATABASE_URL: postgresql://postgres:postgres@localhost:5432/db
    product_service:
        build: ./product_service
        volumes:
           - ./product_service/:/app
        ports:
            - "8002:8000"
        environment:
            DATABASE_URL: postgresql://postgres:postgres@localhost:5432/db

